using BookStoreApplicationOriginal.Models;

namespace BookStoreApplicationOriginal.Repository
{
    public class BookRepository
    {
        public List<BooksModel> GetAllBooks() 
        {
            return _books();
        }
        public BooksModel GetBookById(int id) 
        {
            return _books().Where(x => x.Id == id ).FirstOrDefault();
        }

        public List<BooksModel> SearchBooks(string title, string authorName)
        {
            return _books().Where(x=> x.Title == title || x.Author ==  authorName).ToList(); 
        }

        private List<BooksModel> _books()
        {
            return new List<BooksModel>
            {
                new BooksModel(){Id=1,ImagePath="https://m.media-amazon.com/images/I/71ItzTRahnL._AC_UY327_FMwebp_QL65_.jpg",Title="C# 7.0 All-in-One for Dummies",Author="John Paul Mueller", Description="C# know-how is a must if you want to be a professional Microsoft developer. It's also good to know a little C# if you're building tools for the web, mobile apps or other development tasks. This reference offers a deep dive into C# for coders still learning the nuances of the valuable programming language. Pop it open to get an intro into coding with C#, how to design secure apps and databases and even pointers on building web and mobile apps with C#.",Amount=580.00f},
                new BooksModel(){Id=2,ImagePath="https://m.media-amazon.com/images/I/81Cipy7LUKS._AC_UY327_FMwebp_QL65_.jpg",Title="Beginning C# and .NET",Author="Benjamin Perkins and Jon D. Reid",Description="Get a running start to learning C# programming with this fun and easy-to-read guide  As one of the most versatile and powerful programming languages around, you might think C# would be an intimidating language to learn. It doesn’t have to be!  In Beginning C# and .NET: 2021 Edition, expert Microsoft programmer and engineer Benjamin Perkins and program manager Jon D. Reid walk you through the precise, step-by-step directions you’ll need to follow to become fluent in the C# language and .NET.  Using the proven WROX method, you’ll discover how to understand and write simple expressions and functions, debug programs, work with classes and class members, work with Windows forms, program for the web, and access data. You’ll even learn about some of the new features included in the latest releases of C# and .NET, including data consumption, code simplification, and performance.  The book also offers:  Detailed discussions of programming basics, like variables, flow control, and object-oriented programming that assume no previous programming experience  “Try it Out” sections to help you write useful programming code using the steps you’ve learned in the book  Downloadable code examples from   Perfect for beginning-level programmers who are completely new to C#, Beginning C# and .NET: 2021 Edition is a must-have resource for anyone interested in learning programming and looking for a fun and intuitive place to start. ",Amount = 4512.00f},
                new BooksModel(){Id=3,ImagePath="https://m.media-amazon.com/images/I/71FVhGLOEKL._AC_UY327_FMwebp_QL65_.jpg",Title="Head First C#",Author="Andrew Stellman",Description="Dive into C# and create apps, user interfaces, games, and more using this fun and highly visual introduction to C#, .NET Core, and Visual Studio. With this completely updated guide, which covers C# 8.0 and Visual Studio 2019, beginning programmers like you will build a fully functional game in the opening chapter. Then you'll learn how to use classes and object-oriented programming, create 3D games in Unity, and query data with LINQ. And you'll do it all by solving puzzles, doing hands-on exercises, and building real-world applications. By the time you're done, you'll be a solid C# programmer--and you'll have a great time along the way!",Amount = 2200.00f},
                new BooksModel(){Id=4,ImagePath="https://m.media-amazon.com/images/I/61FQsUySmRL._AC_UY327_FMwebp_QL65_.jpg",Title="C# 10 in a Nutshell",Author="Joseph Albahari",Description="When you have questions about C# 10 or .NET 6, this best-selling guide has the answers you need. C# is a language of unusual flexibility and breadth, and with its continual growth, there's always so much more to learn. In the tradition of O'Reilly's Nutshell guides, this thoroughly updated edition is simply the best one-volume reference to the C# language available today.",Amount = 2800.00f},
                new BooksModel(){Id=5,ImagePath="https://m.media-amazon.com/images/I/81JHhR6gmOL._AC_UY327_FMwebp_QL65_.jpg",Title="C# GAME PROGRAMMING COOKBOOK FOR UNITY 3D",Author="Jeff W. Murray",Description="This second edition of C# Game Programming Cookbook for Unity 3D expounds upon the first with more details and techniques. With a fresh array of chapters, updated C# code and examples, Jeff W. Murray’s book will help the reader understand structured game development in Unity unlike ever before.\r\n\r\nNew to this edition is a step-by-step tutorial for building a 2D infinite runner game from the framework and scripts included in the book. The book contains a flexible and reusable framework in C# suitable for all game types. From game state handling to audio mixers to asynchronous scene loading, the focus of this book is building a reusable structure to take care of many of the most used systems.\r\n\r\nImprove your game's sound in a dedicated audio chapter covering topics such as audio mixers, fading, and audio ducking effects, or dissect a fully featured racing game with car physics, lap counting, artificial intelligence steering behaviors, and game management. Use this book to guide your way through all the required code and framework to build a multi-level arena blaster game.",Amount = 10120.00f},
                new BooksModel(){Id=6,ImagePath="https://m.media-amazon.com/images/I/71lKR6JWtWL._AC_UY327_FMwebp_QL65_.jpg",Title="C# 4.0 THE COMPLETE REFERENCE",Author="Herbert Schildt",Description="The Definitive Guide to C#Bestselling author Herb Schildt has updated and expanded his classic programming reference to cover C# 4.0--the latest release of this powerful, feature-rich language. Using carefully crafted explanations, insider tips, and hundreds of examples, C# 4.0: The Complete Reference offers in-depth details on all aspects of C#, including keywords, syntax, and core libraries. New C# 4.0 features, such as named and optional arguments, the dynamic type, expanded covariance and contravariance capabilities, and support for parallel programming with the Task Parallel Library (TPL) and PLINQ are also discussed.Perfect for beginners and professional C# programmers alike, this expert resource is written in the clear, crisp, uncompromising style that has made Herb the choice of millions worldwide. Begin mastering C# 4.0 today with help from this authoritative volume!Herbert Schildt is a leading authority on C#, C++, C, and Java. His programming books have sold millions of copies worldwide and have been translated into all major languages. Herb is the author of numerous bestsellers, including Java: The Complete Reference, C++: The Complete Reference, C: The Complete Reference; and Java: a Beginner's Guide. Find out more at www.HerbS.",Amount = 853.13f},
                new BooksModel(){Id=7,ImagePath="https://m.media-amazon.com/images/I/611QwyNLoaL._AC_UY327_FMwebp_QL65_.jpg",Title="Mastering C# 4.0 with Complete C# Language and Examples",Author="Webtech Solutions Inc.",Description="Table of Contents Introduction to C# 4.0 Introducing classes and objects Arrays and Strings Operator overloading String and controls in C# Inheritance Exception Handling Using Input/Output Strings & Formating Multithread Programming Collections Enumerators and Ilterators",Amount = 180.00f},
                new BooksModel(){Id=8,ImagePath="https://m.media-amazon.com/images/I/61zAUG0zdyL._AC_UY327_FMwebp_QL65_.jpg",Title="C# 11 and .NET 7 – Modern Cross-Platform Development Fundamentals",Author="Mark J. Price ",Description="Extensively revised to accommodate the latest features that come with C# 11 and .NET 7, this latest edition of our guide will get you coding in C# with confidence.\r\n\r\nYou'll learn object-oriented programming, writing, testing, and debugging functions, implementing interfaces, and inheriting classes. Next, you'll take on .NET APIs for performing tasks like managing and querying data, working with the filesystem, and serialization. As you progress, you'll also explore examples of cross-platform projects you can build and deploy, such as websites and services using ASP.NET Core.\r\n\r\nInstead of distracting you with unnecessary graphical user interface code, the first eleven chapters will teach you about C# language constructs and many of the .NET libraries through simple console applications. Having mastered the basics, you'll then start building websites, web services, and browser apps.\r\n\r\nBy the end of this book, you'll be able to create rich web experiences and have a solid grasp of object-oriented programming that you can build upon.",Amount = 938.69f}
            };
        }

    }
}
